name: Miri Unit Test

on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/test.yml"
    branches:
      - "**"
  pull_request:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          components: miri
          toolchain: nightly
      - name: Cache cargo registry, index, and targets
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          prefix-key: "cargo-miri"
      - name: Run Miri tests
        run: |
          RUST_BACKTRACE=1 \
          MIRIFLAGS="-Zmiri-backtrace=full" \
          cargo +nightly miri test --all --locked --verbose
        shell: bash
